name: Test Init Script

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main ]

jobs:
  test-init-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Test init script with --skip
      run: |
        npm run init -- --skip
        
    - name: Verify data directory structure
      run: |
        echo "Checking data directory structure..."
        ls -la data/
        ls -la data/profile/
        ls -la data/articles/
        ls -la data/community/
        
    - name: Verify TypeScript compilation
      run: npx tsc --noEmit
      
    - name: Verify build works
      run: npm run build
